#!/usr/bin/env python3
"""
Test script for GoogleSearcher class.
This demonstrates how to use the GoogleSearcher to process multiple queries from an AI model.
"""

from GoogleSearcher import GoogleSearcher
from typing import List


def process_ai_generated_questions(questions: List[str], num_results: int = 3) -> dict:
    """
    Process a list of questions from an AI model and retrieve relevant URLs.
    
    Args:
        questions: List of questions generated by an AI model
        num_results: Number of URLs to retrieve per question
        
    Returns:
        Dictionary mapping each question to its relevant URLs
    """
    # Initialize the searcher with default settings
    searcher = GoogleSearcher()
    
    # Process all questions in batch
    results = searcher.batch_search(questions, num_results_per_query=num_results)
    
    return results


def main():
    # Example: List of questions that might come from an AI model
    ai_generated_questions = [
        "Comment créer une entreprise en France ?",
        "Quelles sont les aides pour les auto-entrepreneurs ?",
        "Quelles sont les démarches pour une déclaration de TVA ?",
        "Comment obtenir un numéro SIRET ?",
        "Quelles sont les obligations comptables d'une SAS ?"
    ]
    
    # Process the questions
    results = process_ai_generated_questions(ai_generated_questions)
    
    # Display results
    print(f"Processed {len(results)} questions:\n")
    
    for question, urls in results.items():
        print(f"Question: {question}")
        if urls:
            print(f"Found {len(urls)} relevant URLs:")
            for i, url in enumerate(urls, 1):
                print(f"  {i}. {url}")
        else:
            print("No relevant URLs found.")
        print()


if __name__ == "__main__":
    main()
